require "dirtydentist.dd"

function init(self)
	msg.post(".", "acquire_input_focus")
	jedilist = {
		"Luke Skywalker",
		"Obi-Wan Kenobi",
		"Yoda",
		"Anakin Skywalker",
		"Mace Windu",
		"Qui-Gon Jinn",
		"Rey",
		"Ahsoka Tano",
		"Ki-Adi-Mundi",
		"Plo Koon",
		"Kit Fisto",
		"Shaak Ti",
		"Aayla Secura",
		"Luminara Unduli",
		"Ezra Bridger",
		"Kanan Jarrus",
		"Cal Kestis",
		"Jolee Bindo",
		"Bastila Shan",
		"Barriss Offee",
		"Saesee Tiin",
		"Agen Kolar",
		"A'Sharad Hett",
		"Stass Allie",
		"Quinlan Vos",
		"Depa Billaba",
		"Adi Gallia",
		"Eeth Koth",
		"Kazdan Paratus",
		"Yaddle"
	}
	dropdown_init(self, "ddEtt", jedilist, true)
	dropdown_init(self, "ddTva", {"ett","två"}, true)
	dropdown_init(self, "ddTre", {"ett","två"}, true)
	dropdown_init(self, "ddFyra", {"ett","två"}, true)
	dropdown_init(self, "comboEtt", jedilist, true)
	dropdown_init(self, "comboTva", jedilist, true)
	dropdown_init(self, "comboTre", jedilist, true)
	dropdown_init(self, "comboFyra", jedilist, true)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)

end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	dropdown_interact(self, action_id, action, "ddEtt",jedilist, true)
	dropdown_interact(self, action_id, action, "ddTva",{"ett","två"},true)
	dropdown_interact(self, action_id, action, "ddTre",{"ett","två"},true)
	dropdown_interact(self, action_id, action, "ddFyra",jedilist,true)
	
	textbox_input(self, action_id, action, "box", true)
	text_input(self, action_id, action, "input", true)

	combobox_interact(self, action_id, action, "comboEtt", jedilist,true)
	combobox_interact(self, action_id, action, "comboTva", jedilist,true)
	combobox_interact(self, action_id, action, "comboTre", jedilist,false)
	combobox_interact(self, action_id, action, "comboFyra", jedilist,true)

	button_touch(self, action_id, action, "buttonEtt", true)

	checkbox(self, action_id, action, "checkEtt", true)

	radio(self, action_id, action, 1, {"radioEtt", "radioTva"}, true)
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
